<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SQ1HPPK" failures="2" tests="4" name="ArithMeticOps" time="0.101" errors="0" timestamp="2023-04-13T08:31:09 IST">
  <testcase classname="com.testng.demo.TestNGDemo1" name="myTestCase1" time="0.013"/>
  <testcase classname="com.testng.demo.TestNGDemo1" name="myTestCase2" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [0] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [10]
at com.testng.demo.TestNGDemo1.myTestCase2(TestNGDemo1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myTestCase2 -->
  <testcase classname="com.testng.demo.TestNGDemo2" name="myTestCase3" time="0.001"/>
  <testcase classname="com.testng.demo.TestNGDemo2" name="myTestCase4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [0] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [10]
at com.testng.demo.TestNGDemo2.myTestCase4(TestNGDemo2.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- myTestCase4 -->
</testsuite> <!-- ArithMeticOps -->
